### ISSUE TITLE
Create a listserv for the Bay Area

### ISSUE THREAD

**Issue by 3vivekb** [codeforsanjose/OSM-SouthBay#2]
Get the community together!

**Comment by 1ec5** [comment]
I sent a request to Michael Collinson to create a talk-us-sfbay mailing list.

**Comment by 1ec5** [comment]
The mailing list is all set up: https://lists.openstreetmap.org/listinfo/talk-us-sfbay/

I’ve also [announced the new list](https://lists.openstreetmap.org/pipermail/talk-us/2017-August/017705.html) on the talk-us list.
